image:
  - Visual Studio 2017
platform:
  - x86
  - x64
configuration:
  - Debug
  - Release
build:
  project: CPPTraits.sln
before_build:
  - nuget restore
for:
  -
    matrix:
      only:
        - platform: x86
    test_script:
      - '%APPVEYOR_BUILD_FOLDER%\Build\32\%CONFIGURATION%\CPPTraitsTests.exe'
  -
    matrix:
      only:
        - platform: x64
    test_script:
      - '%APPVEYOR_BUILD_FOLDER%\Build\64\%CONFIGURATION%\CPPTraitsTests.exe'
